service: hackh-broadcast-node
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
functions:
  status:
    handler: functions/Status/index.handler
    events:
      - http:
          path: api/status
          method: get
  Auth/otp:
    handler: functions/Auth/otp.handler
    events:
      - http:
          path: api/otp
          method: post
plugins:
  - serverless-offline
